version: '3'

services:
  producer:
    build:
      context: ./producer-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - my_network

  consumer:
    build:
      context: ./consumer-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - producer
    networks:
      - my_network

networks:
  my_network:
