services:
  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - '5777:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123postgres
      POSTGRES_DB: test-dev
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_data:
